export const CLEAR_RESERVATIONS = "CLEAR_RESERVATIONS";
export const SAVE_RESERVATIONS = "SAVE_RESERVATIONS";
export const CREATE_USER = "CREATE_USER";
export const DELETE_USER = "DELETE_USER";
export const CLEAR_USERS = "CLEAR_USERS";